AllCops:
    TargetRubyVersion: 2.5.3
    Exclude:
        - db/migrate/*
        - db/schema.rb
        - db/seeds/*
        - bin/**/*
        - vendor/bundle/**/*

Rails:
    Enabled: true

Style/FrozenStringLiteralComment:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Style/Documentation:
    Enabled: false

Metrics/LineLength:
    Max: 120
